import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/Carousel";
import NavbarNext from "../components/NavbarNext";
import FooterNext from '../components/FooterNext'
import WhyNext from "../components/WhyNext";
import VideoNext from "../components/VideoNext";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Girl Power Talk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <VideoNext />
        <NavbarNext />
        <Carousel />
        <WhyNext />
      </main>

      <footer>
        <FooterNext />
      </footer>
    </div>
  );
}
